[tools]
claude = "latest"
codex = "latest"
go = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
# check https://helm.sh/docs/topics/version_skew/#supported-version-skew when updating
helm = "4.2"
kubectl = "1.34"
node = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"pipx:aec-cli" = "latest"
"pipx:confluence-markdown-exporter" = "latest"
"pipx:cruft" = "latest"
"pipx:nbdime" = "latest"
rust = "latest"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
