[tools]
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
node = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"pipx:aec-cli" = "latest"
"pipx:nbdime" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
