# setup tools
brew "stow"
brew "duti"
brew "antidote"

# cli tools
brew "fzf"
brew "ripgrep"
brew "wget"
brew "jq"
brew "jless"
brew "yq"
brew "scmpuff"
brew "sd"
brew "gh"
brew "zoxide"
brew "diff-so-fancy"
brew "saulpw/vd/visidata"
brew "hyperfine"
brew "grpcurl"
brew "pstree"
brew "direnv"
brew "dust"

# encryption/security
brew "age"
brew "age-plugin-yubikey"
brew "ykman"
cask "yubico-authenticator"
## gnu-getopt and tree are needed for passage
brew "gnu-getopt"
brew "tree"
cask "1password-cli"
cask "1password"

# aws
brew "awscli"
cask "session-manager-plugin", args: {'no-quarantine': true}
cask "aws-vault-binary"

# dev tools
brew "shellcheck"
cask "beyond-compare"
brew "nvim"
cask "visual-studio-code"
## for vscode symbol generation
brew "ctags"
brew "hashicorp/tap/terraform"
brew "pandoc"
brew "wiggle"
## later version than apple git
brew "git"
brew "git-lfs"

# docker
cask "docker"
brew "hadolint"
brew "crane"
brew "dive"

# handy kubernetes tools
brew "k9s"
brew "helm"
brew "k3d"
## do not install dependencies, ie: kubernetes-cli, because we do so in kubectl.sh
brew "kubectx", args: ["ignore-dependencies"]
brew "stern"

# python
brew "python@3.9"
brew "python@3.10"
brew "python@3.11"
brew "python@3.12"
brew "pyenv"
brew "pipx"

# needed for building some python packages
brew "automake"
brew "libtool"

# node
brew "node"
brew "yarn"
brew "fnm"

# java
cask "temurin@11"

# golang
brew "go"
brew "gopls"
brew "staticcheck"
cask "goreleaser/tap/goreleaser"

# mac desktop apps
cask "calibre"
cask "dropbox"
cask "firefox"
cask "google-drive"
cask "google-chrome" unless system "[[ -d '/Applications/Google Chrome.app' ]]"
cask "iterm2"
cask "cleanshot"
cask "macbreakz"
cask "slack" unless system "[[ -d '/Applications/Slack.app' ]]"
cask "spotify"
cask "iina"
cask "whatsapp"
cask "zoom" unless system "[[ -d '/Applications/zoom.us.app' ]]"

vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "kddejong.vscode-cfn-lint"
vscode "hashicorp.terraform"
vscode "streetsidesoftware.code-spell-checker"
vscode "tekumara.typos-vscode"
vscode "fwcd.kotlin"
vscode "foxundermoon.shell-format"
vscode "timonwong.shellcheck"
vscode "redhat.vscode-yaml"
vscode "davidanson.vscode-markdownlint"
vscode "mhutchie.git-graph"
vscode "esbenp.prettier-vscode"
vscode "njpwerner.autodocstring"
vscode "ziyasal.vscode-open-in-github"
vscode "tomoyukim.vscode-mermaid-editor"
vscode "ms-vscode-remote.remote-ssh"
vscode "exiasr.hadolint"
vscode "tamasfe.even-better-toml"
vscode "mikestead.dotenv"
vscode "sourcery.sourcery"
vscode "adpyke.vscode-sql-formatter"
vscode "Cardinal90.multi-cursor-case-preserve"
