# setup tools
brew "stow"
brew "duti"
brew "antibody"

# cli tools
brew "fzf"
brew "ripgrep"
brew "wget"
brew "jq"
brew "jless"
brew "yq"
brew "mdcat"
brew "scmpuff"
brew "gh"
brew "zoxide"
brew "diff-so-fancy"
brew "saulpw/vd/visidata"
brew "xsv"
brew "hyperfine"
brew "grpcurl"
brew "pstree"
brew "direnv"

# encryption/security
brew "age"
brew "age-plugin-yubikey"
brew "ykman"
cask "homebrew/cask-drivers/yubico-authenticator"
## gnu-getopt and tree are needed for passage
brew "gnu-getopt"
brew "tree"
brew "lastpass-cli"
brew "1password/tap/1password-cli"
cask "authy"

# aws
brew "awscli"
cask "session-manager-plugin", args: {'no-quarantine': true}
cask "aws-vault"
brew "cfn-lint"

# dev tools
brew "shellcheck"
cask "intellij-idea-ce"
cask "visual-studio-code"
cask "beyond-compare"
## for vscode symbol generation
brew "ctags"
brew "nbdime"
## don't install on m1 mac because of https://github.com/giltene/wrk2/issues/120
brew "jabley/homebrew-wrk2/wrk2", args: ["HEAD"] unless system '[[ "$(/usr/bin/uname -m)" == "arm64" ]]'
brew "terraform"
brew "pandoc"
## later version than apple git
brew "git"
brew "git-lfs"

cask "docker"
brew "hadolint"
brew "crane"
brew "dive"

# handy kubernetes tools
brew "k9s"
brew "helm"
brew "k3d"
## do not install dependencies, ie: kubernetes-cli, because we do so in kubectl.sh
brew "kubectx", args: ["ignore-dependencies"]
brew "stern"

# python
brew "pyenv"
brew "pyenv-virtualenvwrapper"
brew "pipx"

# needed for building some python packages
brew "automake"
brew "libtool"

# node
brew "node"
brew "yarn"
brew "Schniz/tap/fnm"

# java
cask "AdoptOpenJDK/openjdk/adoptopenjdk11"
brew "coursier/formulas/coursier"

# golang
brew "go"
brew "gopls"
brew "staticcheck"
brew "goreleaser/tap/goreleaser"

# rust
brew "rust"
brew "rustfmt"

# mac desktop apps
cask "calibre"
cask "dropbox"
cask "firefox"
## run go2shell manually after first install to add to Finder
cask "go2shell"
cask "google-drive"
cask "google-chrome" unless system "[[ -d '/Applications/Google Chrome.app' ]]"
cask "iterm2"
cask "licecap"
cask "macbreakz"
cask "slack" unless system "[[ -d '/Applications/Slack.app' ]]"
cask "spotify"
cask "vlc"
cask "whatsapp"
cask "zoom" unless system "[[ -d '/Applications/zoom.us.app' ]]"
