# setup tools
brew "stow"
brew "duti"
brew "antibody"

# cli tools
brew "fzf"
brew "ripgrep"
brew "wget"
brew "jq"
brew "mdcat"
brew "scmpuff"
brew "gh"
brew "zoxide"
brew "diff-so-fancy"

# aws
brew "awscli"
cask "session-manager-plugin", args: {'no-quarantine': true}
cask "aws-vault"
brew "cfn-lint"

# dev tools
brew "shellcheck"
cask "beyond-compare"
# for vscode symbol generation
brew "ctags"
brew "nbdime"
tap "jabley/homebrew-wrk2"
# don't install on m1 mac because of https://github.com/giltene/wrk2/issues/120
brew "wrk2", args: ["HEAD"] unless system '[[ "$(/usr/bin/uname -m)" == "arm64" ]]'
brew "pandoc"
# later version than apple git
brew "git"
brew "git-lfs"
brew "hadolint"

# handy kubernetes tools
brew "kubectx"
brew "k9s"
brew "helm"
brew "k3d"

cask "docker"

# python
brew "pyenv"
brew "pyenv-virtualenvwrapper"
brew "pipx"

# node
brew "node"
brew "yarn"
brew "Schniz/tap/fnm"

# needed for building some python packages
brew "automake"
brew "libtool"

# java
tap "AdoptOpenJDK/openjdk"
cask "adoptopenjdk11"
brew "coursier/formulas/coursier"

# golang
brew "go"
brew "staticcheck"
brew "goreleaser/tap/goreleaser"

# install mac apps
cask "authy"
cask "calibre"
cask "dropbox"
cask "firefox"
cask "go2shell"
cask "google-drive"
cask "google-chrome" unless system "[[ -d '/Applications/Google Chrome.app' ]]"
cask "intellij-idea-ce"
cask "iterm2"
cask "licecap"
cask "macbreakz"
cask "slack" unless system "[[ -d '/Applications/Slack.app' ]]"
cask "spotify"
cask "visual-studio-code"
cask "vlc" unless system "[[ -d '/Applications/VLC.app' ]]"
cask "whatsapp"
